### ISSUE TITLE
Investigate if a WebAssembly can be build from SCL Auto Alignment Service

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-auto-alignment#24]
As a OpenSCD User
I would like to make use of the SCL Auto Alignment Service without backend
So that Auto Alignment will work without a backend in the browser

It would be nice to have some kind of WebAssembly available to make it possible to run the Auto Algnment Service in OpenSCD directly.
Some Technics to create a WebAssembly are:
- https://github.com/konsoletyper/teavm
- https://leaningtech.com/cheerpj/
- https://github.com/i-net-software/JWebAssembly
- https://cytoscape.org/

**Comment by Sander3003** [comment]
No priority for now.

**Comment by dlabordus** [comment]
Don't see the need anymore to create a WebAssembly. If the OpenSCD project wants this we can always discuss it.
