### ISSUE TITLE
Get X/Y Coordinates from PowSyBl for PowerTransformers

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-auto-alignment#29]
As a Engineer
I would like the PowerTransformers to be correctly positioned
So that the SLD is drawn correctly

Currently PowSyBl isn't returning the location (X/Y Coordinates) for PowerTransformers at Substation Level.
So we kind of put them our self at some location.

There is a issue created for this by PowSyBl (https://github.com/powsybl/powsybl-single-line-diagram/issues/322).
Hopefully the information is added to the JSON so we can use it.

**Comment by flo-dup** [comment]
Thanks for creating the issue on powsybl :+1:  The corresponding issue powsybl/powsybl-single-line-diagram#322 has been solved in a PR which has been merged today to main branch. Next release (expected by the end of the week) will contain the fix.

**Comment by flo-dup** [comment]
The 2.7.0 version of single-line-diagram has been released yesterday on maven central; it contains the fix as expected.
